version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    labels:
      - area/dependencies
    ignore:
      - dependency-name: *:*
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "01:30"
      timezone: Europe/Paris
    open-pull-requests-limit: 2
    labels:
      - area/infra
