image: eclipse-temurin:17

pipelines:
  default:
  - step:
      caches:
        - maven
      script:
        - ./mvnw -P validate -B clean verify
  branches:
    master:
    - step:
        caches:
        - maven
        script:
        - ./mvnw -P validate -B clean verify
    develop:
    - step:
        caches:
        - maven
        script:
        - ./mvnw -P validate -B clean verify
    feature/*:
    - step:
        caches:
        - maven
        script:
        - ./mvnw -P validate -B clean verify
    bugfix/*:
    - step:
        caches:
        - maven
        script:
        - ./mvnw -P validate -B clean verify