FROM adoptopenjdk/openjdk11:x86_64-ubi-minimal-jdk-11.0.8_10

MAINTAINER First8 B.V.

ENV DOCKERIZE_OPTS ""
ENV DOCKERIZE_VERSION v0.6.1
RUN curl -OL https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
   && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

COPY entry.sh /

VOLUME [ "/app" ]
WORKDIR /app
ENTRYPOINT [ "/entry.sh" ]

CMD ["-?" ]