package nl.moj.server.message.model;

public enum MessageType {
    COMPILE, TEST, SUBMIT, TIMER_SYNC, START_ASSIGNMENT, STOP_ASSIGNMENT, TEAM_STARTED_TESTING, START_ASSIGNMENT_FAILED,
    TESTING_STARTED,TESTING_ENDED,COMPILING_STARTED,COMPILING_ENDED,SUBMIT_STARTED,SUBMIT_ENDED;

}
